// Song database for Nakuru Intro Quiz - with discography info, start times & volume normalization
const SONGS = [
  {"id":"Nymzuz3u7RE","title":"Cadeau de Dieu","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":"","start":1.2,"vol":0.79},
  {"id":"fz_hqEdn87M","title":"わがままモザイク","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":"","start":1,"vol":0.88},
  {"id":"cAGuLsSlO3Q","title":"ジョーカー・パレード","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":"","start":1.2,"vol":0.93},
  {"id":"2yy9uajYF7E","title":"星空のアナグラム","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017) / 作曲: はるなば","lyrics":"","start":1.4},
  {"id":"BFV-3m_XqFM","title":"ふたりのラクエン","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":"","start":1.5,"vol":0.89},
  {"id":"y_y154nynLQ","title":"ガラスアゲハ","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":"","start":1.4,"vol":1.09},
  {"id":"olWljQJxe_k","title":"Satellite Connect","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":"","start":1.4,"vol":0.69},
  {"id":"WaPNkjY3gNk","title":"その名はRendezvous","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":"","start":1.2,"vol":1.05},
  {"id":"fgXnq8I2HWk","title":"エーテル","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":"","start":1.3},
  {"id":"WFgqAGx6330","title":"JelLaboratory","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":"","start":2,"vol":1.1},
  {"id":"3KYwAkMAiw0","title":"Cornus Florida","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":1.24},
  {"id":"K5tz4AGdBE0","title":"リフレクション","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.63},
  {"id":"1nxZietohec","title":"Alt.Strato","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":1.79},
  {"id":"tayIKdDnOw8","title":"泡沫の灯","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":1.2},
  {"id":"eRylytyGelM","title":"桜色プリズム (2017 Spring Edition)","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.75},
  {"id":"9ihgjLuL1rg","title":"一粒の今","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":0.9,"vol":1.79},
  {"id":"L2eh4l0Z3qU","title":"Fatalism","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":"","start":3.1,"vol":0.76},
  {"id":"6PXwuFRXGs8","title":"floating outsider","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":0.86},
  {"id":"m3lUO6Lw85k","title":"残光","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":"","start":0.4,"vol":0.7},
  {"id":"53-b8JvP990","title":"終点前","category":"endorfin","info":"Endorfin. EP「Stories of Eve」収録 (2019) / 作曲: sky_delta","lyrics":"","vol":0.8},
  {"id":"YhmKNyPwJ4s","title":"M:routine","category":"endorfin","info":"Endorfin. EP「Stories of Eve」収録 (2019) / 作曲: sky_delta","lyrics":"","start":3.6,"vol":1.2},
  {"id":"15PzGHhrlVo","title":"Horizon Claire","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.91},
  {"id":"XiEWp1NNt0U","title":"彗星のパラソル","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":"","start":0.7,"vol":2.33},
  {"id":"g-cfAT6HuaQ","title":"Hypnotic Marmalade Jam","category":"endorfin","info":"Endorfin. EP「純情ティータイム」収録 (2018) / 作曲: sky_delta","lyrics":"","start":0.4,"vol":0.61},
  {"id":"VJc7hCoT_Zw","title":"LØST-IDEA","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":"","vol":0.81},
  {"id":"pdY4eLvUbnc","title":"ユリシス","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":"","start":0.3,"vol":0.7},
  {"id":"vxX7Cs21wgQ","title":"Kaleidoscope","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"LFqhjgRlDQA","title":"カラフルモーメント","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.91},
  {"id":"sLHBK8pf90o","title":"絵空","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":0.76},
  {"id":"_Xe70bzLPh4","title":"純情ティータイム","category":"endorfin","info":"Endorfin. EP「純情ティータイム」収録 (2018) / 作曲: sky_delta","lyrics":"","vol":0.7},
  {"id":"sx5mfcw_BCQ","title":"薄明が告げる明日に","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":"","vol":1.24},
  {"id":"lBMpjQsHnfQ","title":"Horizon Note","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":0.8,"vol":0.72},
  {"id":"6wLqyUPtTIM","title":"桜色プリズム","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":0.8,"vol":0.76},
  {"id":"SM7qCdawIfY","title":"Luminous Rage","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":0.7,"vol":0.75},
  {"id":"aPtVQ2Hdczg","title":"Spica","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":0.7,"vol":0.79},
  {"id":"Vz10PdNRto0","title":"コトノハ","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":"","start":1,"vol":1.05},
  {"id":"TJVPcRcW3Z8","title":"海月","category":"endorfin","info":"6thアルバム「Transpain」収録 (2021) / 作曲: m@sumi","lyrics":"","start":1.1,"vol":1.2},
  {"id":"vSPgbN_QoYM","title":"Raindrop Caffé Latte","category":"endorfin","info":"6thアルバム「Transpain」収録 (2021) / 作曲: 高城みよ","lyrics":"","start":0.6,"vol":0.87},
  {"id":"cDfUxfV514g","title":"Spring for you","category":"endorfin","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":"","start":0.6,"vol":0.76},
  {"id":"U5YMCw0kD2E","title":"春風ファンタジア","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":"","start":0.7,"vol":0.73},
  {"id":"tV-e7E3OuH8","title":"わたしがわたしに至った10の理由","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.6,"vol":0.64},
  {"id":"0OKo4iie8kU","title":"Azura Luno","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.5,"vol":0.91},
  {"id":"Pmkp2-Fe1j8","title":"whisper","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.5,"vol":0.93},
  {"id":"6Jfd0Ar3luQ","title":"Folded Wings","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.6,"vol":0.83},
  {"id":"JFqKLwmDX1Y","title":"フェイク","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.5,"vol":0.71},
  {"id":"WlfX_d_0BiM","title":"Lilith","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":"","start":0.4,"vol":0.78},
  {"id":"DSTs43vxfvY","title":"モノローグ・オフ","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":2.01},
  {"id":"Sg5EK3koalc","title":"Alice's Suitcase","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / Arcaea収録曲 / 作曲: sky_delta","lyrics":"","start":0.4,"vol":0.63},
  {"id":"O9x8thg8ZHE","title":"惑星トリップ","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":"","start":0.8,"vol":0.77},
  {"id":"ptPU_yz3yfQ","title":"Round & Round","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":"","start":0.9,"vol":1.1},
  {"id":"zPr2QiSwVFI","title":"アンダーマリン","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":"","start":2.1,"vol":1.07},
  {"id":"Cb5v-I5BLFo","title":"Drop Role","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: m@sumi","lyrics":""},
  {"id":"IrQbmLbbjpw","title":"Transpain","category":"solo","info":"6thアルバム「Transpain」タイトル曲 (2021)","lyrics":"","start":0.4,"vol":1.81},
  {"id":"lRUugzV0w9A","title":"Othello syndrome","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: sky_delta","lyrics":"","start":0.9,"vol":1.16},
  {"id":"i8YIp3AUMiM","title":"ガラスアゲハ (Feryquitous JazzRemix)","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":"","vol":0.66},
  {"id":"3KZOQJ_1xgw","title":"mirror","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: 高城みよ","lyrics":"","vol":0.84},
  {"id":"Xjfm-ylgq9E","title":"Evil Bubble","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":"","vol":1.17},
  {"id":"7wOgIwM4mgM","title":"Oxydlate","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":""},
  {"id":"ZgH3RN-dg5A","title":"Defective","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: Tansa","lyrics":"","start":0.7,"vol":0.94},
  {"id":"Q5BvmJHybBY","title":"花残り、蕾ひとつ","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","start":0.8,"vol":0.8},
  {"id":"UHkfyQkhnQA","title":"コンティニュー！","category":"endorfin","info":"Endorfin. / 作曲: lapix / 音ゲー収録曲","lyrics":"","start":1,"vol":0.72},
  {"id":"LcK_WTNC1DA","title":"アンチグレーズ","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":2.36},
  {"id":"cSueFHyhyVE","title":"Killer neuron","category":"solo","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 佐高陵平","lyrics":"","start":0.7,"vol":0.87},
  {"id":"W-Jm3-IYXO8","title":"route signal","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","start":0.5},
  {"id":"74hLJEHF-AE","title":"Settlement","category":"solo","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 板倉孝徳","lyrics":"","start":0.5,"vol":2.36},
  {"id":"XZPDODSgdoo","title":"夢の呼応","category":"solo","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 櫻澤ヒカル","lyrics":"","vol":2.5},
  {"id":"oNBXsTA7qXc","title":"Codependence","category":"solo","info":"アルバム「Indigrotto」収録 (2022) / 作曲: Feryquitous","lyrics":"","start":0.5,"vol":1.28},
  {"id":"hrWRWdDdZdw","title":"Transistor","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","vol":0.79},
  {"id":"tioxzasntss","title":"サニーサイド・クローバー","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","start":0.4,"vol":1.25},
  {"id":"xNfXmtDOoGU","title":"a fairy with you","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":"","start":0.9,"vol":1.3},
  {"id":"FPL1Z_w7k4g","title":"Rest in Peace my Dear","category":"solo","info":"アルバム「Indigrotto」収録 (2022) / 作曲: グシミヤギヒデユキ (Hifumi,inc.)","lyrics":"","start":1,"vol":0.84},
  {"id":"4P1OdtYncNY","title":"Indigrotto","category":"solo","info":"アルバム「Indigrotto」タイトル曲 (2022) / 作曲: 北川勝利","lyrics":"","vol":0.89},
  {"id":"63gXH5Rylf4","title":"ペトリコール","category":"endorfin","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 佐高陵平","lyrics":"","start":0.3,"vol":2.05},
  {"id":"7XeWXV_9mOY","title":"FAKE IDOL","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: Akki","lyrics":"","start":1.6,"vol":1.54},
  {"id":"vO5DYcS72Xk","title":"ミントブルー・ガール","category":"endorfin","info":"アルバム「Indigrotto」収録 (2022) / 作曲: Feryquitous","lyrics":"","start":0.7,"vol":0.85},
  {"id":"7-i1DQVm5Ew","title":"シュガーレス・レイン","category":"endorfin","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 板倉孝徳","lyrics":"","start":0.6,"vol":1.63},
  {"id":"OuJRu0g61QM","title":"無言の鳥籠","category":"endorfin","info":"アルバム「Indigrotto」収録 (2022) / 作曲: 櫻澤ヒカル","lyrics":"","start":0.6,"vol":1.31},
  {"id":"j45s9xvJ4Mk","title":"秒針とソーダフロート","category":"endorfin","info":"アルバム「Indigrotto」収録 (2022) / 作曲: グシミヤギヒデユキ (Hifumi,inc.)","lyrics":"","start":0.7,"vol":1.12},
  {"id":"T3lI7lh_3UA","title":"Dirt","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: Feryquitous","lyrics":"","start":1.1,"vol":1.05},
  {"id":"sadX5FgzxyY","title":"唾と蜜","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: samayuzame","lyrics":""},
  {"id":"PeZzdoP-gKk","title":"Bad Drip","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: K's","lyrics":"","start":6.8},
  {"id":"6SwJlZyMHqQ","title":"Domination","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: Osanzi","lyrics":"","vol":0.69},
  {"id":"E8eVpmmdMeY","title":"Fragile Utopia","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: mami","lyrics":"","start":0.6,"vol":0.9},
  {"id":"KF0kZrffZBo","title":"Lucid Hallucination","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: 高城みよ","lyrics":"","start":0.6,"vol":0.8},
  {"id":"ypSeH9kz2Oo","title":"逆沙華","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: Feryquitous","lyrics":"","start":0.7,"vol":0.94},
  {"id":"DowXn2fHDWU","title":"Tuliparfeit","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: かめりあ (Camellia)","lyrics":"","start":0.5,"vol":0.65},
  {"id":"1iYy09QIJqw","title":"ミシュメリア","category":"solo","info":"アルバム「ミシュメリア」タイトル曲 (2023) / 作曲: bermei.inazawa","lyrics":"","start":1.2,"vol":1.08},
  {"id":"wHThc6MPuPc","title":"オッドアイ・リリィ","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: グシミヤギヒデユキ","lyrics":"","start":0.8,"vol":0.7},
  {"id":"iynq12bYTHk","title":"雷花","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":"","start":0.4},
  {"id":"ikwQHfccAqg","title":"Untitled Sky","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":"","start":0.7,"vol":1.08},
  {"id":"7s3eA2XeH78","title":"ハートレス・トリコロール","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.67},
  {"id":"O9XuzOv6Y3A","title":"ペンと林檎とわたし","category":"solo","info":"カバー / 原曲: Akki (幽谷きらら名義) / クトゥルフ神話TRPGシナリオ関連曲 / もこ田めめめとの「歌ってみた」","lyrics":"","start":0.6,"vol":1.33},
  {"id":"AVM65BGXWKo","title":"ストレンジレッド","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":"","start":0.8,"vol":0.74},
  {"id":"Gcx5pL2Wydw","title":"Apricot","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":"","start":1.1,"vol":0.88},
  {"id":"V9-HBgFbhqg","title":"トワイライト","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous","lyrics":"","start":0.4,"vol":0.61},
  {"id":"Wh88hMIsm1k","title":"Monodrate","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous","lyrics":"","start":1.4,"vol":1.18},
  {"id":"_4n1xG4YnA4","title":"閃耀 (Cover)","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous / カバー","lyrics":"","vol":0.74},
  {"id":"bEuwswhL8Rk","title":"何も知らないまま。","category":"solo","info":"初の全国流通ソロシングル (2024) / 作曲: Haniwa（アメリカ民謡研究会）","lyrics":"","start":0.7,"vol":1.81},
  {"id":"-F3NV1ls41c","title":"愛の残滓","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 作曲: 佐高陵平 / ゲーム「魔法少女ノ魔女裁判」挿入歌","lyrics":"","vol":1.08},
  {"id":"S8MJvhgjXBY","title":"Chronologue","category":"la_priere","info":"La prière 3rdアルバム「Chronologue」タイトル曲 (2022) / 12ヶ月連続リリース最終月(2022年3月) / 作曲: Tansa","lyrics":"","start":2.1,"vol":2.01},
  {"id":"Ft1oytmXg3Y","title":"Instant Love","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年7月 / 作曲: aran","lyrics":"","start":1.3,"vol":0.71},
  {"id":"OIXr7nJDHwQ","title":"Dead Scream","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年5月 / 作曲: Tansa","lyrics":"","start":2.6,"vol":1.41},
  {"id":"5Gl7HppdYh0","title":"來人具惨（RisingSun）","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年8月 / 作曲: RD-Sounds","lyrics":"","start":1.1,"vol":0.83},
  {"id":"Ol1N6shDJ94","title":"純情アンビバレンス","category":"la_priere","info":"La prière デジタルシングル (2026) / 作曲: satella / 作詞: Feryquitous / 3ヶ月連続リリース第2弾","lyrics":"","start":0.6,"vol":1.2},
  {"id":"fuDMqXHk5Pc","title":"Flyby Anomaly","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年4月 / 作曲: かそかそ","lyrics":"","start":0.7,"vol":1.58},
  {"id":"_xyaWcdPlZI","title":"GHOST","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年6月 / 作曲: n.k","lyrics":"","start":0.4},
  {"id":"YGJScjjp5Lc","title":"禁断の愛と魔剣","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年10月 / 作曲: 塚越雄一朗","lyrics":"","start":0.3,"vol":0.82},
  {"id":"cWvUa-_Zayw","title":"アルビレオ","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年11月 / 作曲: Feryquitous","lyrics":"","start":0.9,"vol":1.3},
  {"id":"xCVBxGOCGm0","title":"Time Lapse Lights","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年12月 / 作曲: 森本練","lyrics":"","start":1.6,"vol":2.5},
  {"id":"PVHnsNkVrcc","title":"無法地点","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2022年1月 / 作曲: 新田目駿","lyrics":"","start":0.6,"vol":0.88},
  {"id":"KzT3O5-PaTw","title":"点心爛漫！ふぁんはおれ","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年9月 / 作曲: かそかそ","lyrics":"","start":0.4,"vol":0.92},
  {"id":"48mx0ODWwEY","title":"Ritus Inanis","category":"la_priere","info":"La prière デジタルシングル (2026) / 作曲: satella / 作詞: Feryquitous / 3ヶ月連続リリース第2弾","lyrics":"","start":2.4,"vol":1.2},
  {"id":"efNl6gpXyJY","title":"snowloop*","category":"itsukinkuru","info":"いつきんくる シングル (2025) / 作曲: picco, Reno / 作詞: purini, Mi7s3","lyrics":"","start":1.2,"vol":0.7},
  {"id":"U6q9Y5PWfkI","title":"追想のラグナロク","category":"itsukinkuru","info":"いつきんくる 1stコラボシングル (2023) / 作曲: 佐高陵平 (Hifumi,inc.) / 作詞: 藍月なくる, 棗いつき","lyrics":"","start":0.4,"vol":0.74},
  {"id":"TRgYfYp2ijc","title":"ヘヴンリィ","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: フユウ","lyrics":"","vol":0.75},
  {"id":"Xly_DiIq-3Y","title":"ルナティッククレイジー (Cover)","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: lapix & Zekk","lyrics":"","vol":0.72},
  {"id":"p3PcGOOoRX0","title":"Cosmodiver","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: かそかそ","lyrics":"","vol":1.28},
  {"id":"WlngSLFuBQ4","title":"水彩のカナリア","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":0.88},
  {"id":"kz1w8DVtK1Q","title":"蛍火の雪","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","start":0.5,"vol":0.64},
  {"id":"qDhwSD0cQUE","title":"パラサイトブルー","category":"solo","info":"カバー / 原曲: Akki (幽谷きらら名義) / クトゥルフ神話TRPGシナリオ関連曲 / もこ田めめめとの「歌ってみた」","lyrics":"","start":0.6,"vol":0.93},
  {"id":"PI096zvC-Mw","title":"スローアライズ","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":0.88},
  {"id":"XTAQbUN_KQY","title":"citron","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","vol":0.84},
  {"id":"Tt2aO7PDejg","title":"COLOURS","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":1.56},
  {"id":"RjwW018sVBk","title":"フラフィ","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":"","start":0.6,"vol":1.24},
  {"id":"QpQVf8BY7jQ","title":"Draw World!","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":10.1,"vol":1.17},
  {"id":"9LRLn4Ku1bw","title":"ドリームブルー","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.8},
  {"id":"wtqC1ccd0JA","title":"タイニーソング","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.9,"vol":1.41},
  {"id":"yZg6n_EhpGQ","title":"ゴースト・マキアート","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.7},
  {"id":"WV1q-_Zf5Mc","title":"空白少女","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":1.3,"vol":1.17},
  {"id":"HMJe2jp0XCg","title":"Focus on","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.8},
  {"id":"7v81QOVx4WE","title":"ヘイマルメネー","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: kaztora（森羅万象）","lyrics":"","start":0.5,"vol":0.73},
  {"id":"OV238oKZj5U","title":"ミスリルドロップ","category":"solo","info":"Endorfin. EP「Horizon Dream」収録 (2025) / 作曲: sky_delta / 活動10周年記念楽曲 / 1stワンマンライブテーマ曲","lyrics":"","start":0.4,"vol":0.79},
  {"id":"Q0iw9_rvqeo","title":"軌跡","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: Feryquitous","lyrics":"","start":0.4},
  {"id":"QJOXcl_TpXU","title":"Predatory","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: wotaku","lyrics":"","vol":0.68},
  {"id":"eIoxs9in7VI","title":"アンチテール","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.4,"vol":0.86},
  {"id":"z5Z2lXGXXMA","title":"Seed of Fate","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: 高城みよ","lyrics":"","start":0.4,"vol":1.36},
  {"id":"8Zh9zsbuhBM","title":"クラリムステラ","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 作曲: sky_delta / サークル名「クラリムステラ」を冠した書き下ろし新曲","lyrics":"","start":0.5,"vol":0.91},
  {"id":"E0SEBm6dUSE","title":"ご注文はえいえんに","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 作曲: 一二三 / ファンミ「ご注文はえいえんに！〜深海喫茶なく茶屋へようこそ〜」テーマソング","lyrics":"","start":0.5,"vol":0.64},
  {"id":"PLkBTrdQiC0","title":"エモーション・キャプチャー","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: kaztora（森羅万象）","lyrics":"","start":0.7,"vol":0.67},
  {"id":"QxXC8g9K0-Q","title":"乖離光(2025 arrange ver)","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: 西憂花","lyrics":"","start":0.5,"vol":0.81},
  {"id":"RPaZQQFwBzw","title":"真相","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: Feryquitous","lyrics":"","start":1.1,"vol":0.94},
  {"id":"fAKfq6Ij-PU","title":"Mirroring Mirage","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: wotaku","lyrics":"","start":0.6,"vol":0.73},
  {"id":"hI_CCMKiUII","title":"Bubble Bubble Boy","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: sky_delta","lyrics":"","start":0.6},
  {"id":"wuIUyGQb6qQ","title":"永劫不可逆","category":"solo","info":"ストーリーアルバム「わたしとキミの幸せな終末」収録 (2025) / 作曲: 高城みよ","lyrics":"","start":0.6,"vol":1.25},
  {"id":"3RuCaE5ciNU","title":"Horizon Dream","category":"endorfin","info":"Endorfin. EP「Horizon Dream」収録 (2025) / 作曲: sky_delta / 活動10周年記念 & 1stワンマンライブテーマ曲","lyrics":"","start":2.1,"vol":2.03},
  {"id":"SMpdghcsays","title":"終点前 -Piano Arrange-","category":"endorfin","info":"いつきんくる シングル (2025) / 作曲: picco, Reno / 作詞: purini, Mi7s3","lyrics":"","start":0.6,"vol":1.83},
  {"id":"UtOS1jb4tfg","title":"純情ティータイム -2025 Live ver.-","category":"endorfin","info":"いつきんくる 1stコラボシングル (2023) / 作曲: 佐高陵平 (Hifumi,inc.) / 作詞: 藍月なくる, 棗いつき","lyrics":"","start":0.6,"vol":1.17},
  {"id":"3osyYQQXCx0","title":"Luminous Rage -2025 Live ver.-","category":"endorfin","info":"ベストアルバム「真相」収録 (2025) / 作曲: sky_delta / サークル名でもある「クラリムステラ」を冠した書き下ろし新曲","lyrics":"","start":0.5,"vol":0.72},
  {"id":"Yq-ZqMh6vXQ","title":"太陽のない夏みたいな僕を","category":"endorfin","info":"ベストアルバム「真相」収録 (2025) / 作曲: 一二三 / ファンミーティング「ご注文はえいえんに！〜深海喫茶なく茶屋へようこそ〜」テーマソング","lyrics":"","start":0.5,"vol":1.81},
  {"id":"KYtXc1vXnAo","title":"ハルラ","category":"endorfin","info":"ベストアルバム「真相」収録 (2025) / 作曲: グシミヤギヒデユキ / 書き下ろし新曲","lyrics":"","start":1.2},
  {"id":"eRlzyMmdzXY","title":"ある夏のエピローグ","category":"endorfin","info":"ベストアルバム「真相」収録 (2025) / 原曲: Feryquitous / 2025アレンジ: にお / 原曲はコラボアルバム「soleil de minuit」(2017)初収録","lyrics":"","start":0.7,"vol":2.5},
  {"id":"C7dRhYYNDIs","title":"サマーエンディング","category":"endorfin","info":"ベストアルバム「真相」表題曲 (2025) / 作曲: にお / ワンマンライブで初披露","lyrics":"","start":0.3,"vol":0.75},
  {"id":"1peOuXyMAIA","title":"八月と青とラムネ","category":"endorfin","info":"ベストアルバム「真相」収録 (2025) / 作曲: 日高勇輝 (Elements Garden) / 作詞: 織田あすか / 2ndライブ「鏡像崇拝」メインテーマ曲","lyrics":"","start":0.6,"vol":0.8},
  {"id":"Ki-ah4cTK9Q","title":"Dear The Night I Loved","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 作曲: Giga & TeddyLoid / 作詞: 児玉雨子 / 書き下ろし新曲","lyrics":"","start":0.7,"vol":0.92},
  {"id":"XHIKQGMBkJc","title":"煌命残滓","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 作曲: にお / 書き下ろし新曲","lyrics":"","start":1.2,"vol":0.81},
  {"id":"6XQkgz2vmiA","title":"幻想ラチェット","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作曲: 香椎モイミ","lyrics":"","start":0.7,"vol":0.84},
  {"id":"KD_Jx-F8blQ","title":"ロマネスクミラージュ","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作詞: 棗いつき / 作曲: グシミヤギ ヒデユキ","lyrics":""},
  {"id":"kMyxu2wyMDg","title":"ILLUAMOR","category":"solo","info":"9thアルバム「ILLUAMOR」タイトル曲 (2026) / 作曲: Laur","lyrics":"","start":1.2,"vol":1.33},
  {"id":"m2SzpAagRKQ","title":"なくなっちゃった。","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作曲: アメリカ民謡研究会","lyrics":"","start":0.6,"vol":0.75},
  {"id":"k29Dog51qwE","title":"Galactic Love","category":"la_priere","info":"La prière 2ndアルバム「Galaxy Triangle」収録 (2020) / 作曲: lapix","lyrics":"","start":1.2,"vol":1.63},
  {"id":"SCu2-Dg03FI","title":"バッドビートベイビー","category":"la_priere","info":"La prière デジタルシングル (2026) / 作曲: 夏山よつぎ","lyrics":"","start":0.6,"vol":0.67},
  {"id":"ZgbQcvtndI4","title":"Hookah, whoo!","category":"collab","info":"ゲーム「Hookah Haze」主題歌 (2024) / 作詞: DECO*27 / 作曲: tepe","lyrics":"","start":0.3,"vol":0.58}
];
