// Song database for Nakuru Intro Quiz - with discography info
const SONGS = [
  {"id":"Nymzuz3u7RE","title":"Cadeau de Dieu","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":""},
  {"id":"fz_hqEdn87M","title":"わがままモザイク","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":""},
  {"id":"cAGuLsSlO3Q","title":"ジョーカー・パレード","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":""},
  {"id":"2yy9uajYF7E","title":"星空のアナグラム","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017) / 作曲: はるなば","lyrics":""},
  {"id":"BFV-3m_XqFM","title":"ふたりのラクエン","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":""},
  {"id":"y_y154nynLQ","title":"ガラスアゲハ","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":""},
  {"id":"olWljQJxe_k","title":"Satellite Connect","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":""},
  {"id":"WaPNkjY3gNk","title":"その名はRendezvous","category":"solo","info":"3rdアルバム「Nacollection!! 2」収録 (2017)","lyrics":""},
  {"id":"fgXnq8I2HWk","title":"エーテル","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":""},
  {"id":"WFgqAGx6330","title":"JelLaboratory","category":"solo","info":"4thアルバム「JelLaboratory」収録 (2018)","lyrics":""},
  {"id":"3KYwAkMAiw0","title":"Cornus Florida","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"K5tz4AGdBE0","title":"リフレクション","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"1nxZietohec","title":"Alt.Strato","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"tayIKdDnOw8","title":"泡沫の灯","category":"endorfin","info":"Endorfin.「Alt.Strato」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"eRylytyGelM","title":"桜色プリズム (2017 Spring Edition)","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":""},
  {"id":"9ihgjLuL1rg","title":"一粒の今","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"L2eh4l0Z3qU","title":"Fatalism","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":""},
  {"id":"6PXwuFRXGs8","title":"floating outsider","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":""},
  {"id":"m3lUO6Lw85k","title":"残光","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":""},
  {"id":"53-b8JvP990","title":"終点前","category":"endorfin","info":"Endorfin. EP「Stories of Eve」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"YhmKNyPwJ4s","title":"M:routine","category":"endorfin","info":"Endorfin. EP「Stories of Eve」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"15PzGHhrlVo","title":"Horizon Claire","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":""},
  {"id":"XiEWp1NNt0U","title":"彗星のパラソル","category":"endorfin","info":"Endorfin.「Horizon Claire」収録 (2020) / 作曲: sky_delta","lyrics":""},
  {"id":"g-cfAT6HuaQ","title":"Hypnotic Marmalade Jam","category":"endorfin","info":"Endorfin. EP「純情ティータイム」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"VJc7hCoT_Zw","title":"LØST-IDEA","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"pdY4eLvUbnc","title":"ユリシス","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"vxX7Cs21wgQ","title":"Kaleidoscope","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"LFqhjgRlDQA","title":"カラフルモーメント","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"sLHBK8pf90o","title":"絵空","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"_Xe70bzLPh4","title":"純情ティータイム","category":"endorfin","info":"Endorfin. EP「純情ティータイム」収録 (2018) / 作曲: sky_delta","lyrics":""},
  {"id":"sx5mfcw_BCQ","title":"薄明が告げる明日に","category":"endorfin","info":"Endorfin.「LOST-IDEA」収録 (2019) / 作曲: sky_delta","lyrics":""},
  {"id":"lBMpjQsHnfQ","title":"Horizon Note","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"6wLqyUPtTIM","title":"桜色プリズム","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"SM7qCdawIfY","title":"Luminous Rage","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"aPtVQ2Hdczg","title":"Spica","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"Vz10PdNRto0","title":"コトノハ","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"TJVPcRcW3Z8","title":"海月","category":"endorfin","info":"Endorfin. 1stアルバム「Horizon Note」収録 (2016) / 作曲: sky_delta","lyrics":""},
  {"id":"vSPgbN_QoYM","title":"Raindrop Caffé Latte","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":""},
  {"id":"cDfUxfV514g","title":"Spring for you","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":""},
  {"id":"U5YMCw0kD2E","title":"春風ファンタジア","category":"endorfin","info":"Endorfin. ミニアルバム「Raindrop Caffé Latte」収録 (2017) / 作曲: sky_delta","lyrics":""},
  {"id":"tV-e7E3OuH8","title":"わたしがわたしに至った10の理由","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"0OKo4iie8kU","title":"Azura Luno","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"Pmkp2-Fe1j8","title":"whisper","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"6Jfd0Ar3luQ","title":"Folded Wings","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"JFqKLwmDX1Y","title":"フェイク","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"WlfX_d_0BiM","title":"Lilith","category":"solo","info":"5thアルバム「Nacollection -3-」収録 (2020)","lyrics":""},
  {"id":"DSTs43vxfvY","title":"モノローグ・オフ","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":""},
  {"id":"Sg5EK3koalc","title":"Alice's Suitcase","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / Arcaea収録曲 / 作曲: sky_delta","lyrics":""},
  {"id":"O9x8thg8ZHE","title":"惑星トリップ","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":""},
  {"id":"ptPU_yz3yfQ","title":"Round & Round","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":""},
  {"id":"zPr2QiSwVFI","title":"アンダーマリン","category":"endorfin","info":"Endorfin.「モノローグ・オフ」収録 (2021) / 作曲: sky_delta","lyrics":""},
  {"id":"Cb5v-I5BLFo","title":"Drop Role","category":"solo","info":"6thアルバム「Transpain」収録 (2021)","lyrics":""},
  {"id":"IrQbmLbbjpw","title":"Transpain","category":"solo","info":"6thアルバム「Transpain」タイトル曲 (2021)","lyrics":""},
  {"id":"lRUugzV0w9A","title":"Othello syndrome","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: sky_delta","lyrics":""},
  {"id":"i8YIp3AUMiM","title":"ガラスアゲハ (Feryquitous JazzRemix)","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":""},
  {"id":"3KZOQJ_1xgw","title":"mirror","category":"solo","info":"6thアルバム「Transpain」収録 (2021)","lyrics":""},
  {"id":"Xjfm-ylgq9E","title":"Evil Bubble","category":"solo","info":"6thアルバム「Transpain」収録 (2021)","lyrics":""},
  {"id":"7wOgIwM4mgM","title":"Oxydlate","category":"solo","info":"6thアルバム「Transpain」収録 (2021) / 作曲: Feryquitous","lyrics":""},
  {"id":"ZgH3RN-dg5A","title":"Defective","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022)","lyrics":""},
  {"id":"Q5BvmJHybBY","title":"花残り、蕾ひとつ","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"UHkfyQkhnQA","title":"コンティニュー！","category":"endorfin","info":"Endorfin. / 作曲: lapix / 音ゲー収録曲","lyrics":""},
  {"id":"LcK_WTNC1DA","title":"アンチグレーズ","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"cSueFHyhyVE","title":"Killer neuron","category":"solo","info":"アルバム「Indigrotto」収録 (2022)","lyrics":""},
  {"id":"W-Jm3-IYXO8","title":"route signal","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"74hLJEHF-AE","title":"Settlement","category":"solo","info":"アルバム「Indigrotto」収録 (2022)","lyrics":""},
  {"id":"XZPDODSgdoo","title":"夢の呼応","category":"solo","info":"アルバム「Indigrotto」収録 (2022)","lyrics":""},
  {"id":"oNBXsTA7qXc","title":"Codependence","category":"solo","info":"アルバム「Indigrotto」収録 (2022)","lyrics":""},
  {"id":"hrWRWdDdZdw","title":"Transistor","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"tioxzasntss","title":"サニーサイド・クローバー","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"xNfXmtDOoGU","title":"a fairy with you","category":"endorfin","info":"Endorfin. COLOURS.01「Growing」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"FPL1Z_w7k4g","title":"Rest in Peace my Dear","category":"solo","info":"アルバム「Indigrotto」収録 (2022)","lyrics":""},
  {"id":"4P1OdtYncNY","title":"Indigrotto","category":"solo","info":"アルバム「Indigrotto」タイトル曲 (2022)","lyrics":""},
  {"id":"63gXH5Rylf4","title":"ペトリコール","category":"endorfin","info":"Endorfin. COLOURS.02「Blurred Mind」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"7XeWXV_9mOY","title":"FAKE IDOL","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022)","lyrics":""},
  {"id":"vO5DYcS72Xk","title":"ミントブルー・ガール","category":"endorfin","info":"Endorfin. COLOURS.02「Blurred Mind」2022 Edition (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"7-i1DQVm5Ew","title":"シュガーレス・レイン","category":"endorfin","info":"Endorfin. COLOURS.02「Blurred Mind」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"OuJRu0g61QM","title":"無言の鳥籠","category":"endorfin","info":"Endorfin. COLOURS.02「Blurred Mind」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"j45s9xvJ4Mk","title":"秒針とソーダフロート","category":"endorfin","info":"Endorfin. COLOURS.02「Blurred Mind」収録 (2022) / 作曲: sky_delta","lyrics":""},
  {"id":"T3lI7lh_3UA","title":"Dirt","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022)","lyrics":""},
  {"id":"sadX5FgzxyY","title":"唾と蜜","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022)","lyrics":""},
  {"id":"PeZzdoP-gKk","title":"Bad Drip","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022)","lyrics":""},
  {"id":"6SwJlZyMHqQ","title":"Domination","category":"solo","info":"7thアルバム「Counterfeit」収録 (2022) / 作曲: Osanzi","lyrics":""},
  {"id":"E8eVpmmdMeY","title":"Fragile Utopia","category":"solo","info":"アルバム「ミシュメリア」収録 (2023)","lyrics":""},
  {"id":"KF0kZrffZBo","title":"Lucid Hallucination","category":"solo","info":"アルバム「ミシュメリア」収録 (2023)","lyrics":""},
  {"id":"ypSeH9kz2Oo","title":"逆沙華","category":"solo","info":"アルバム「ミシュメリア」収録 (2023) / 作曲: Feryquitous","lyrics":""},
  {"id":"DowXn2fHDWU","title":"Tuliparfeit","category":"solo","info":"アルバム「ミシュメリア」収録 (2023)","lyrics":""},
  {"id":"1iYy09QIJqw","title":"ミシュメリア","category":"solo","info":"アルバム「ミシュメリア」タイトル曲 (2023)","lyrics":""},
  {"id":"wHThc6MPuPc","title":"オッドアイ・リリィ","category":"solo","info":"アルバム「ミシュメリア」収録 (2023)","lyrics":""},
  {"id":"iynq12bYTHk","title":"雷花","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"ikwQHfccAqg","title":"Untitled Sky","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"7s3eA2XeH78","title":"ハートレス・トリコロール","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"O9XuzOv6Y3A","title":"ペンと林檎とわたし","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"AVM65BGXWKo","title":"ストレンジレッド","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"Gcx5pL2Wydw","title":"Apricot","category":"endorfin","info":"Endorfin. COLOURS.03「Redraw」収録 (2023) / 作曲: sky_delta","lyrics":""},
  {"id":"V9-HBgFbhqg","title":"トワイライト","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous","lyrics":""},
  {"id":"Wh88hMIsm1k","title":"Monodrate","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous","lyrics":""},
  {"id":"_4n1xG4YnA4","title":"閃耀 (Cover)","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: Feryquitous / カバー","lyrics":""},
  {"id":"bEuwswhL8Rk","title":"何も知らないまま。","category":"solo","info":"2024年リリース","lyrics":""},
  {"id":"-F3NV1ls41c","title":"愛の残滓","category":"solo","info":"ベストアルバム「真相」収録 (2025) / ゲーム挿入歌","lyrics":""},
  {"id":"S8MJvhgjXBY","title":"Chronologue","category":"la_priere","info":"La prière 3rdアルバム「Chronologue」タイトル曲 (2022) / 12ヶ月連続リリース最終月(2022年3月) / 作曲: Tansa","lyrics":""},
  {"id":"Ft1oytmXg3Y","title":"Instant Love","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年7月 / 作曲: aran","lyrics":""},
  {"id":"OIXr7nJDHwQ","title":"Dead Scream","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年5月 / 作曲: Tansa","lyrics":""},
  {"id":"5Gl7HppdYh0","title":"來人具惨（RisingSun）","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年8月 / 作曲: RD-Sounds","lyrics":""},
  {"id":"Ol1N6shDJ94","title":"純情アンビバレンス","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2022年2月 / 作曲: かそかそ","lyrics":""},
  {"id":"fuDMqXHk5Pc","title":"Flyby Anomaly","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年4月 / 作曲: かそかそ","lyrics":""},
  {"id":"_xyaWcdPlZI","title":"GHOST","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年6月 / 作曲: n.k","lyrics":""},
  {"id":"YGJScjjp5Lc","title":"禁断の愛と魔剣","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年10月 / 作曲: 塚越雄一朗","lyrics":""},
  {"id":"cWvUa-_Zayw","title":"アルビレオ","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年11月 / 作曲: Feryquitous","lyrics":""},
  {"id":"xCVBxGOCGm0","title":"Time Lapse Lights","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年12月 / 作曲: 森本練","lyrics":""},
  {"id":"PVHnsNkVrcc","title":"無法地点","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2022年1月 / 作曲: 新田目駿","lyrics":""},
  {"id":"KzT3O5-PaTw","title":"点心爛漫！ふぁんはおれ","category":"la_priere","info":"La prière / 12ヶ月連続リリース 2021年9月 / 作曲: かそかそ","lyrics":""},
  {"id":"48mx0ODWwEY","title":"Ritus Inanis","category":"la_priere","info":"La prière / 2026年リリース","lyrics":""},
  {"id":"efNl6gpXyJY","title":"snowloop*","category":"itsukinkuru","info":"いつきんくる（棗いつき × 藍月なくる）","lyrics":""},
  {"id":"U6q9Y5PWfkI","title":"追想のラグナロク","category":"itsukinkuru","info":"いつきんくる 1stシングル (2023)","lyrics":""},
  {"id":"TRgYfYp2ijc","title":"ヘヴンリィ","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: フユウ","lyrics":""},
  {"id":"Xly_DiIq-3Y","title":"ルナティッククレイジー (Cover)","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: lapix & Zekk","lyrics":""},
  {"id":"p3PcGOOoRX0","title":"Cosmodiver","category":"solo","info":"アルバム「Nacollection4」収録 (2023) / 作曲: かそかそ","lyrics":""},
  {"id":"WlngSLFuBQ4","title":"水彩のカナリア","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"kz1w8DVtK1Q","title":"蛍火の雪","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"qDhwSD0cQUE","title":"パラサイトブルー","category":"solo","info":"藍月なくる オリジナル曲","lyrics":""},
  {"id":"PI096zvC-Mw","title":"スローアライズ","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"XTAQbUN_KQY","title":"citron","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"Tt2aO7PDejg","title":"COLOURS","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"RjwW018sVBk","title":"フラフィ","category":"endorfin","info":"Endorfin. COLOURS.04「Yelling」収録 (2024) / 作曲: sky_delta","lyrics":""},
  {"id":"QpQVf8BY7jQ","title":"Draw World!","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"9LRLn4Ku1bw","title":"ドリームブルー","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"wtqC1ccd0JA","title":"タイニーソング","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"yZg6n_EhpGQ","title":"ゴースト・マキアート","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"WV1q-_Zf5Mc","title":"空白少女","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"HMJe2jp0XCg","title":"Focus on","category":"endorfin","info":"Endorfin.「Dream Blue」収録 (2025) / 作曲: sky_delta","lyrics":""},
  {"id":"7v81QOVx4WE","title":"ヘイマルメネー","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"OV238oKZj5U","title":"ミスリルドロップ","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"Q0iw9_rvqeo","title":"軌跡","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"QJOXcl_TpXU","title":"Predatory","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"eIoxs9in7VI","title":"アンチテール","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"z5Z2lXGXXMA","title":"Seed of Fate","category":"solo","info":"アルバム「わたしとキミの幸せな終末」収録 (2025)","lyrics":""},
  {"id":"8Zh9zsbuhBM","title":"クラリムステラ","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"E0SEBm6dUSE","title":"ご注文はえいえんに","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"PLkBTrdQiC0","title":"エモーション・キャプチャー","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"QxXC8g9K0-Q","title":"乖離光(2025 arrange ver)","category":"solo","info":"ベストアルバム「真相」収録 (2025) / 新アレンジ","lyrics":""},
  {"id":"RPaZQQFwBzw","title":"真相","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"fAKfq6Ij-PU","title":"Mirroring Mirage","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"hI_CCMKiUII","title":"Bubble Bubble Boy","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"wuIUyGQb6qQ","title":"永劫不可逆","category":"solo","info":"ベストアルバム「真相」収録 (2025)","lyrics":""},
  {"id":"3RuCaE5ciNU","title":"Horizon Dream","category":"endorfin","info":"Endorfin. / 作曲: sky_delta","lyrics":""},
  {"id":"SMpdghcsays","title":"終点前 -Piano Arrange-","category":"endorfin","info":"Endorfin. 終点前 ピアノアレンジ / 作曲: sky_delta","lyrics":""},
  {"id":"UtOS1jb4tfg","title":"純情ティータイム -2025 Live ver.-","category":"endorfin","info":"Endorfin. 2025 Live ver. / 作曲: sky_delta","lyrics":""},
  {"id":"3osyYQQXCx0","title":"Luminous Rage -2025 Live ver.-","category":"endorfin","info":"Endorfin. 2025 Live ver. / 作曲: sky_delta","lyrics":""},
  {"id":"Yq-ZqMh6vXQ","title":"太陽のない夏みたいな僕を","category":"endorfin","info":"Endorfin.「Cirro.Strato」収録 (2026) / 作曲: sky_delta","lyrics":""},
  {"id":"KYtXc1vXnAo","title":"ハルラ","category":"endorfin","info":"Endorfin.「Cirro.Strato」収録 (2026) / 作曲: sky_delta","lyrics":""},
  {"id":"eRlzyMmdzXY","title":"ある夏のエピローグ","category":"endorfin","info":"Endorfin.「Cirro.Strato」収録 (2026) / 作曲: sky_delta","lyrics":""},
  {"id":"C7dRhYYNDIs","title":"サマーエンディング","category":"endorfin","info":"Endorfin.「Cirro.Strato」収録 (2026) / 作曲: sky_delta","lyrics":""},
  {"id":"1peOuXyMAIA","title":"八月と青とラムネ","category":"endorfin","info":"Endorfin.「Cirro.Strato」収録 (2026) / 作曲: sky_delta","lyrics":""},
  {"id":"Ki-ah4cTK9Q","title":"Dear The Night I Loved","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作曲: かぼちゃ","lyrics":""},
  {"id":"XHIKQGMBkJc","title":"煌命残滓","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作詞: 藍月なくる / 作曲: みゅー(Imy)","lyrics":""},
  {"id":"6XQkgz2vmiA","title":"幻想ラチェット","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作曲: 香椎モイミ","lyrics":""},
  {"id":"KD_Jx-F8blQ","title":"ロマネスクミラージュ","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作詞: 棗いつき / 作曲: グシミヤギ ヒデユキ","lyrics":""},
  {"id":"kMyxu2wyMDg","title":"ILLUAMOR","category":"solo","info":"9thアルバム「ILLUAMOR」タイトル曲 (2026) / 作曲: Laur","lyrics":""},
  {"id":"m2SzpAagRKQ","title":"なくなっちゃった。","category":"solo","info":"9thアルバム「ILLUAMOR」収録 (2026) / 作曲: アメリカ民謡研究会","lyrics":""},
  {"id":"k29Dog51qwE","title":"【MV】Galactic Love / lapix feat. La prière","category":"la_priere","info":"La prière 2ndアルバム「Galaxy Triangle」収録 (2020)","lyrics":""},
  {"id":"SCu2-Dg03FI","title":"【MV】バッドビートベイビー / La prière","category":"la_priere","info":"La prière シングル (2026)","lyrics":""},
  {"id":"ZgbQcvtndI4","title":"Hookah, whoo!","category":"collab","info":"ゲーム「Hookah Haze」主題歌 (2024) / 作詞: DECO*27 / 作曲: tepe","lyrics":""}
];
